[[constraint]]
  name = "github.com/asdine/storm"
  version = "2.1.1"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/copier"

[[constraint]]
  branch = "master"
  name = "github.com/novakit/binfs"

[[constraint]]
  branch = "master"
  name = "github.com/novakit/nova"

[[constraint]]
  branch = "master"
  name = "github.com/novakit/router"

[[constraint]]
  branch = "master"
  name = "github.com/novakit/static"

[[constraint]]
  branch = "master"
  name = "github.com/novakit/view"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.14.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[prune]
  go-tests = true
  unused-packages = true
